### ISSUE TITLE
Exception while using ExportItems

### ISSUE THREAD

**Issue by RajatNair** [David-Barrett-MS/SOAPe#2] opened 2020-10-14 17:23 UTC
Hi,

Was trying the ExportItems call but received `The request is invalid` error. 

1. List messages from Inbox - 
Request - 
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <Header xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <RequestServerVersion Version="Exchange2016" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" />
  </Header>
  <soap:Body>
    <FindItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" Traversal="Shallow">
      <ItemShape>
        <t:BaseShape>Default</t:BaseShape>
      </ItemShape>
      <IndexedPageItemView MaxEntriesReturned="50" Offset="0" BasePoint="Beginning" />
      <ParentFolderIds>
        <t:DistinguishedFolderId Id="inbox" />
      </ParentFolderIds>
    </FindItem>
  </soap:Body>
</soap:Envelope>
```
Response (clipped for brevity) -
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo MajorVersion="15" MinorVersion="20" MajorBuildNumber="3455" MinorBuildNumber="31" Version="V2018_01_08" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
  </s:Header>
  <s:Body>
    <m:FindItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:FindItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:RootFolder IndexedPagingOffset="50" TotalItemsInView="1195" IncludesLastItemInRange="false">
            <t:Items>
              <t:Message>
                <t:ItemId Id="AAMkAGJmZWFmZDdjLWM3OWYtNDcyNi04Mjc0LTcyMDE2ZTg2OWI4YQBGAAAAAACdzk37AJWKQJfpSfe5eNnsBwAaDd9JZumVQYWgdVutRE20AAAAAAEMAAAaDd9JZumVQYWgdVutRE20AABkN5ucAAA=" ChangeKey="CQAAABYAAAAaDd9JZumVQYWgdVutRE20AABkGWYg" />
                <t:Subject>Azure AD Identity Protection Weekly Digest</t:Subject>
                <t:Sensitivity>Normal</t:Sensitivity>
                <t:Size>142051</t:Size>
                <t:DateTimeSent>2020-10-13T08:11:46Z</t:DateTimeSent>
                <t:DateTimeCreated>2020-10-13T08:11:53Z</t:DateTimeCreated>
                <t:HasAttachments>false</t:HasAttachments>
                <t:IsAssociated>false</t:IsAssociated>
                <t:From>
                  <t:Mailbox>
                    <t:Name>Microsoft Azure</t:Name>

```

Loaded ExportItems template and set the itemid -

Request  - 
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="https://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="https://schemas.microsoft.com/exchange/services/2006/messages">
  <soap:Header>
    <RequestServerVersion Version="Exchange2016" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" />
  </soap:Header>
  <soap:Body>
    <m:ExportItems>
      <m:ItemIds>
        <t:ItemId Id="AAMkAGJmZWFmZDdjLWM3OWYtNDcyNi04Mjc0LTcyMDE2ZTg2OWI4YQBGAAAAAACdzk37AJWKQJfpSfe5eNnsBwAaDd9JZumVQYWgdVutRE20AAAAAAEMAAAaDd9JZumVQYWgdVutRE20AABkN5ucAAA=" />
      </m:ItemIds>
    </m:ExportItems>
  </soap:Body>
</soap:Envelope>
```

Response - 
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <Action s:mustUnderstand="1" xmlns="http://schemas.microsoft.com/ws/2005/05/addressing/none">*</Action>
  </s:Header>
  <s:Body>
    <s:Fault>
      <faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInvalidRequest</faultcode>
      <faultstring xml:lang="en-US">The request is invalid.</faultstring>
      <detail>
        <e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInvalidRequest</e:ResponseCode>
        <e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The request is invalid.</e:Message>
      </detail>
    </s:Fault>
  </s:Body>
</s:Envelope>
```

Any suggestions?

PS:
👍 On keep SOAPe alive

**Comment by David-Barrett-MS** [comment] 2021-01-15 12:16
Sorry I didn't spot this earlier.  I can reproduce the issue, though that's all I can confirm currently.  The request looks correct, and I tested with a request taken from our docs that also returned the error.
It looks like an issue from the Exchange side.  I'll see if I can dig a little deeper and find out what is going wrong.

**Comment by David-Barrett-MS** [comment] 2021-02-11 19:34
I've just pushed a fix into the source code for this.  The issue is in the template.  A couple of the schema references use https instead of http, which causes a fault.  It will be fixed in the next release, but in the meantime you can just change the references in the Xml.

**Closed by David-Barrett-MS** 2021-02-11 19:34 UTC
